openapi: 3.0.1
info:
  title: 지역 음식점 룰렛 추천 API
  description: 홈화면 룰렛으로 음식 카테고리를 무작위 선택하고 해당 카테고리의 음식점을 추천합니다.
  version: 1.0.1

paths:
  /api/roulette/spin:
    get:
      summary: 룰렛 카테고리 미리 보기
      description: 룰렛에 등장할 음식 카테고리(한식, 중식, 양식)를 조회합니다.
      tags: [Roulette]
      responses:
        '200':
          description: 룰렛 가능 카테고리 목록
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  enum: [한식, 중식, 양식]
        '500':
          description: 내부 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: 음식 카테고리 룰렛 실행
      description: 한식, 중식, 양식 중 하나를 룰렛으로 무작위 선택하고 결과를 서버에 기록합니다.
      tags: [Roulette]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                sessionId:
                  type: string
      responses:
        '200':
          description: 선택된 음식 카테고리
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryResult'
        '400':
          description: 잘못된 요청 데이터 (예 잘못된 userId 형식)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: 룰렛 수행 실패 (카테고리 부족 등)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/restaurants:
    get:
      summary: 음식점 카테고리 기반 추천 리스트
      description: 선택된 카테고리에 해당하는 음식점 목록을 반환합니다.
      tags: [Restaurant]
      parameters:
        - name: category
          in: query
          required: true
          schema:
            type: string
            enum: [한식, 중식, 양식]
      responses:
        '200':
          description: 음식점 리스트
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Restaurant'
        '400':
          description: 카테고리 파라미터 누락 또는 유효하지 않음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 해당 카테고리의 음식점 없음
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 내부 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/chatbot/redirect:
    get:
      summary: 챗봇 페이지로 이동
      description: 사용자가 챗봇에게 추가적으로 질문하고 싶은 경우 페이지 링크를 제공합니다.
      tags: [Chatbot]
      responses:
        '200':
          description: 챗봇 페이지 URL 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                    format: uri
        '500':
          description: 서버 오류
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CategoryResult:
      type: object
      properties:
        category:
          type: string
          enum: [한식, 중식, 양식]
          example: 한식
        message:
          type: string
          example: "한식이 선택되었습니다!"

    Restaurant:
      type: object
      properties:
        id:
          type: integer
          example: 101
        name:
          type: string
          example: "김가네 국밥"
        category:
          type: string
          example: "한식"
        address:
          type: string
          example: "경북 경주시 보문로 123"
        phone:
          type: string
          example: "054-123-4567"
        imageUrl:
          type: string
          format: uri
          example: "https://example.com/images/restaurant101.jpg"

    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
          example: 400
        error:
          type: string
          example: "Bad Request"
        message:
          type: string
          example: "카테고리 파라미터는 필수입니다."
        timestamp:
          type: string
          format: date-time
          example: "2025-08-01T13:45:00Z"